### ISSUE TITLE
The 'active' page generates a link

### ISSUE THREAD

**Issue by Lybecker** [ernado-x/X.PagedList#10]
On initial load of a page the active page is 1. Then the page should not be clickable or be generated as an anchor. An empty <a></a> is still clickable. The anchor should not be there.

```
<ul class="pagination">
  <li class="active">
    <a>1</a></li>
    <li><a href="/Student/List?page=2">2</a>
  </li>
</ul>
```

**Comment by ernado-x** [comment]
Closed by c2dcee47f582f2f413774e5073f75efab9f244e0
