### ISSUE TITLE
Center page numbers

### ISSUE THREAD

**Issue by omeshechkov** [ernado-x/X.PagedList#15]
Hello,

Is there a way to center page numbers between prev. button and next button.
Prev. button has float: left,
Next button has float: right;

Thanks.

**Comment by ernado-x** [comment]
I think, you can "override" css classes for setup button postions.

**Comment by omeshechkov** [comment]
It seems I stuck in CSS, I don't know how to align all LIs between first and last.
```html
<ul>
  <li class='nav-button page-number'>Prev</li> <- float: left
  <li class='page-number'>1</li> --
  <li class='page-number'>2</li>   |-- <-- how to align this sequence of LIs?
  <li class='page-number'>3</li> --
  <li class='nav-button page-number'>Next</li> <- float: right
</ul>
```

**Comment by ernado-x** [comment]
Please google for :first-child :last-child selectors for css
