### ISSUE TITLE
PageList.Mvc Namespace missing in 4.9.0.250-beta

### ISSUE THREAD

**Issue by samirageb** [ernado-x/X.PagedList#16]
I experienced the same behavior installing the beta as was described here: https://github.com/ernado-x/X.PagedList/issues/8

After the NuGet install the X.PagedList.Mvc .dll was no longer referenced in my project, the PagedList.Mvc namespace was compl As previously mentioned, the .dll did exist in a net45 directory and manually adding the reference addressed the issue. Perhaps the nuget bundling is the culprit?

**Comment by ernado-x** [comment]
I update packge: https://www.nuget.org/packages/X.PagedList.Mvc/

Please check new version.
