### ISSUE TITLE
Async paged list implementation, allow custom async methods

### ISSUE THREAD

**Issue by guillaume-fr** [ernado-x/X.PagedList#3]
The current async implementation starts a task in a thread and does the work synchronously in this thread. We can often use an underlying async implementation instead of taking a thread (for instance with EF CountAsync / ToListAsync). Also the current implementation will do the Count inside the calling thread, I don't think this was expected.

An abstract AsyncPagedList with abstract methods for CountAsync and ToListAsync so we can add our own implementations without duplicating math on different properties may be usefull ... ?

Also, for your implementation, running the task on another thread, the whole process should be on the other thread and not only ToList : `return Task.Factory.StartNew(() => new StaticPagedList<T>(superset.Skip<T>(((pageNumber - 1) * pageSize)).Take<T>(pageSize), pageNumber, pageSize, superset.Count<T>()));`

**Comment by alexandru-calinoiu** [comment]
I arrived at this issue while searching of the async loading capabilities, the problem the code you mentioned is that it use IEnumerable instead of IQueryable

**Comment by ernado-x** [comment]
Ok, so I reopen this issue and should update code. Or you can make pull request if you wish.

**Comment by alexandru-calinoiu** [comment]
I will probably work on this when I have the chance, I've forked the code and looked around but I still need some time to wrap my head around it.

**Comment by alexandru-calinoiu** [comment]
Opened a pr, please review and let me know, 

I think we need to need that key param and order by, will look around some more.

**Comment by ernado-x** [comment]
I approve your pull request.
