### ISSUE TITLE
Setting PageNumber as int.MaxValue

### ISSUE THREAD

**Issue by migig** [ernado-x/X.PagedList#8]
Strange worked for me before I submitted PR to PagedList project, but now in this library when I do

    someQuery.ToPagedList(int.MaxValue, 100);

then I get exception:

    "Count must have a non-negative value.\r\nParameter name: count"

...Can anyone confirm whether this new feature works for them?

**Comment by migig** [comment]
Ok I think I understand... The version on nuget is from last year! :sob: 

So we need to update the nuget version to the latest... That new version has this new feature.

**Comment by ernado-x** [comment]
@migig , you can find latest build here - https://www.nuget.org/packages/X.PagedList.Mvc/4.9.0.250-beta and here - https://www.nuget.org/packages/X.PagedList/1.24.0.250-beta

**Comment by migig** [comment]
@ernado-x Cool. Looking forward to the final release. Any idea when?

**Comment by migig** [comment]
@ernado-x  Weird, I can't get the ".Mvc" pakcage to install. It says it installs but does not. Does the prerelease nuget actually install for you?

**Comment by migig** [comment]
@ernado-x Yep it looks like the files are in the wrong directory. So they don't get included in the project, and so it is broken... :cry:

**Comment by ernado-x** [comment]
This is not wrong folder. This assembly compiled for .NET 4.5
I tested it in VS 2015 and it work correct - reference was added without problems.

**Comment by migig** [comment]
Thanks for double checking!

Strange. When I install nuget, it adds reference to the Pagelist DLL, but not the Pagedlist.MVC DLL, and so doesn't work. And it points to the wrong folder where there is nothing (content), and the dll is in the lib folder.

I wodner why it works for you and not me.

**Comment by migig** [comment]
No I still get the same error `"Count must have a non-negative value.\r\nParameter name: count"`.

I never get thsi error with the original library, so it must be something new which was added. Wish I knew how to fix it, until then I've gone back to the old version.

**Comment by ernado-x** [comment]
@migig , sorry, I cant test it until weekend. Or, if you wish, you can prepare own nuget package and I upload it to nuget.org.

**Comment by migig** [comment]
@ernado-x No don't worry about it. I have no way of reproducing this problem, so there is no need to waste time on it. For now the old library works for me. I appreciate your help so far. I'll wait to see who else has this issue and then maybe we can fix it.
